### ISSUE TITLE
Bug : Conflict with dorako's UI

### ISSUE THREAD

**Issue by uniwars** [Garsondee/pf2e-roll-manager#10]
Hi, it seems that the module breaks some color in the "Configure settings" menu when dorako's UI is active :

![image](https://github.com/Garsondee/pf2e-roll-manager/assets/65986545/46ea6d78-e534-43fc-a697-c20bd2905f26)
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/65986545/0a480788-652b-4854-9843-22abea02b619)

**Comment by ChasarooniZ** [comment]
Seconding this ^^^

**Comment by Garsondee** [comment]
This absolutely isn't a problem with Dorako or that UI mod - it'll be a CSS mistake in mine. Don't worry, it's high on the list to fix.

**Comment by Garsondee** [comment]
https://github.com/Garsondee/pf2e-roll-manager/releases/tag/v1.2

I think this is now fixed.
