### ISSUE TITLE
[Bug?] Not interacting with PF2e system rolls properly?

### ISSUE THREAD

**Issue by ChasarooniZ** [Garsondee/pf2e-roll-manager#2]
Hi, it appears whatever method you're using to roll isn't interacting with rolls normally as your rolls don't popualte roll options?

![image](https://github.com/Garsondee/pf2e-roll-manager/assets/79132112/a522071c-073d-49b5-9546-f942e0eee0a4)

As an example this is what a normal roll thorugh Acrobatics does

![image](https://github.com/Garsondee/pf2e-roll-manager/assets/79132112/00aec72b-7d15-44f7-9893-0d6a6aa0be2d)

**Comment by ChasarooniZ** [comment]
really like the mod tho

**Comment by Garsondee** [comment]
I'm still very new to module making and the PF2E system in Foundry - I didn't know that a roll inspector exists and I can't find any obvious links to it online. It looks like it would be incredibly helpful for this project. How do you access it?

**Comment by Garsondee** [comment]
Ahh. I now know how to examine the rolls. Are you a programmer or someone used to the PF2E system? I could really do with some help to properly make these rolls work but I don't yet know how to read from the source code to make it work ideally. Even if you could give me an example of how to pass a perception check roll along to the system correctly that would be a good start and something I could work from.

**Comment by ChasarooniZ** [comment]
Taken from the Pf2e discord, you're missing most likely notes and options from when you're constructing the roll?


```javascript
if (!actor) {
  ui.notifications.warn("You must have an actor selected");
} else {
  const skillName = "Occultism";
  const skillKey = "occ";
  const actionSlug = "recall-knowledge"
  const actionName = "Recall Knowledge"

  const modifiers = [
      new game.pf2e.Modifier('Charisma Swap', "@abilities.cha.mod - @abilities.int.mod")
  ]
  // list custom modifiers for a single roll here
  //const modifiers = [
  //new game.pf2e.Modifier('Expanded Healer\'s Tools', 1, 'item')
  //];
  
  const notes = [...token.actor.data.data.skills[skillKey].notes]; // add more notes if necessary
    // Syntax for a note: {"outcome":[], "selector":"crafting", "text":'<p><a class="entity-link" draggable="true" data-entity="Item" data-id="TSxkmgfLWwNQnAnA"> Overdrive II</a><strong>Critical Success</strong></p><p><a class="entity-link" draggable="true" data-entity="Item" data-id="MDGROvBFqiOFm8Iv"> Overdrive I</a><strong>Success</strong></p>'}
  const options = token.actor.getRollOptions(['all', 'skill-check', skillName.toLowerCase()]);
  options.push(`action:${actionSlug}`); // add more traits here in new lines
  // options.push(`secret`); // <--- This is what I am talking about
  game.pf2e.Check.roll(
    new game.pf2e.CheckModifier(
      `<span class="pf2-icon">A</span> <b>${actionName}</b> - <p class="compact-text">${skillName } Skill Check</p>`,
      token.actor.data.data.skills[skillKey], modifiers ),
      { actor: token.actor, type: 'skill-check', options, notes }, // add dc: { value: 25 } in the object to roll against a dc
      event
      //for callback: ,(Roll) => {console.log(Roll);}
  );
}
```Found it

**Comment by ChasarooniZ** [comment]
Not sure if this is the best way, but it'll at least fix some of the missing data as a stopgap

**Comment by Garsondee** [comment]
The rolls are better formed now - probably a lot of room for improvement but I'll close this issue here and work on fixing/adding smaller parts of the roll as I move forwards.

**Comment by ChasarooniZ** [comment]
Alright sounds good, feel free to message me on discord or @me on issues if you have any questions (I'll try my best)
