### ISSUE TITLE
It broke with the 1.3.8 update

### ISSUE THREAD

**Issue by SonofOrion42** [Garsondee/pf2e-roll-manager#33]
For some reason, the new version has left me completely unable to request rolls from players anymore. They don't appear no matter what, whereas before they would always be there, token present or no. The slider color also doesn't scale with the party level anymore, which was extremely handy for telling how difficult a roll would be for PCs of that level, but that's likely caused by the PCs no longer being on the roll manager to begin with. This has happened even with all other modules turned off with the help of Find The Culprit.
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/31265059/64608b97-8331-42e7-beb4-9480d563d7ce)
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/31265059/237fe2ac-5dfc-4e3e-a78e-e72e6c796eb8)

Also, I noticed that the new update moved the manager button to the left sidebar, which is nice and all, but if we could have the option to bring the large green button back to the right sidebar, that'd be awesome. I always thought its high visibility and size made it easier to use, especially since it appeared on every tab, so I didn't have to constantly scramble to go back to a single specific tab to use it while in game. Even if it was optional, that'd be fine, though the module would need an options menu to begin with.

**Comment by Garsondee** [comment]
So as of 1.3.8 the module only shows the tokens which are in the currently active scene and which are owned by a player. Can you check to see if you were trying to open the Roll Manager in a scene without the tokens of the party?

I'll add the option to bring back the big button in the next version hopefully.

**Comment by Garsondee** [comment]
Also if you could check the console (f12) and send me an image if you see any errors there or copy them here that would be very helpful.

**Comment by SonofOrion42** [comment]
That's good to hear. And you're right; with tokens onscreen, it does work. I did like being able to use it without tokens needing to be present, though, like when the players are looking at the world map and there's only the unified party icon to designate their position. Helps streamline things for theater-of-the-mind type stuff, but it's not a huge deal. Thanks!

**Comment by jpmiers** [comment]
This was actually the primary reason I used this module, there are a slew of other ways to roll quickly if the tokens are on the map. This module was the only way to quickly roll for characters NOT on the map. I am sad about this change but I understand why it was made.

**Comment by Garsondee** [comment]
New version uploaded with a complete rewrite. Hopefully that fixes this issue.
