### ISSUE TITLE
[BUG] No Correct roll modifiers

### ISSUE THREAD

**Issue by altair984** [Garsondee/pf2e-roll-manager#34]
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/52784850/e1196410-80b1-4bad-adbf-bb481f2f4674)
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/52784850/de404af8-b4ef-413a-a513-021084ff20a1)
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/52784850/e48d8a7e-9bf0-480a-8ffb-7e6f27775b2e)
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/52784850/da2bae24-ad2e-4c1a-8196-3e217e4e3616)

**Comment by SonofOrion42** [comment]
I've had this issue. However, when you roll skills with these incorrect modifiers, the actual roll doesn't include the preexisting circumstance bonuses unless you select them in the dialog box. So technically, you can still roll normally; it's just that the dropdown box accounts for every bonus a character's skill has, even those that would not be active for specific rolls.

**Comment by Garsondee** [comment]
Complete rewrite of the module done - I can't promise it's perfect but it's much much better at finding the right modifiers now.
