### ISSUE TITLE
"You don't own this token" Message to players when they do i fact own the token

### ISSUE THREAD

**Issue by Proncho** [Garsondee/pf2e-roll-manager#39]
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/36051678/bd291b9e-f5c5-42a5-8bf9-7f3eef30af64)
Everytime I request a roll from a character it gives them the message that they aint the owner. Can anyone help me? Im sorry if this aint the place to ask.

**Comment by Truncated** [comment]
I ran into this in my last game as well. I was running the last versions for V11 foundry of pf2e and the character token had been out but the ownership was changed between players and GM as the normal player was not at game and I was running it as an NPC for that session.

Can you provide more details about the situation, version, etc?

**Comment by Proncho** [comment]
Im also in the last version for v11. It just never lets PCs roll their requested roll as it says they dont own the actor. Havent really changed ownerships at all

**Comment by Garsondee** [comment]
This should be fixed now as I no longer check for character ownership.
