### ISSUE TITLE
Roll Options all selected

### ISSUE THREAD

**Issue by chazpls** [Garsondee/pf2e-roll-manager#4]
Every roll option appears to be selected by default when rolling checks through this prompt. I think that by default, only always-on roll bonuses should be included (such as general item bonuses). A cool potential feature in the future would be to add tags to the roll, which would enable appropriate roll options to be automated.

![image](https://github.com/Garsondee/pf2e-roll-manager/assets/156643689/aaad957e-e58c-41d8-8052-ef825ee16173)

**Comment by Garsondee** [comment]
I'm closing this as stale because the new version should hopefully avoid this situation.
