### ISSUE TITLE
Small QoL suggestions

### ISSUE THREAD

**Issue by 117Dios** [Garsondee/pf2e-roll-manager#45]
This is a lovely module. I had just a few suggestion to make it even better, apologies in advance if you already thought about them or implemented them for v12, as I'm currently using v11.

1 - Switch Perception location
In order to transition the readability from the sheet to the module window, I suggest putting Perception on the same row with the Saving Throws, and maybe putting them all on top, but this last bit I think is optional
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/36032209/0b96882e-aa9b-4556-8cde-f8ed6cdbf516)

2 - Level-based DCs
Ability to choose between party level DCs, level-based DCs and spell-level DCs. There should already be macros that do that around, maybe in workbench, so I think it is easily implementable
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/36032209/68ffa493-8210-4fe7-b77b-35dde735e646)

3 - Character selection options
Make it so that you can choose if you want every character selected or no characters selected when opening the Roll Manager window (or even specific characters selected but I think the first two options are more than enough)

4 - Swap Fixed DCs and Difficulty modifiers
This is more to keep everything that decides a DC in one place and whatever modifies it in another. Difficulty modifiers could even go on top while the rest below, maybe keeping the slider just above the characters
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/36032209/8309e772-cfc6-4256-83ea-3bb6eb1dfc0d)

5 - Make Difficulty modifiers toggles instead of increases
This way we have always under our eyes what we decided to do in case it slips our mind

Again, thanks for the module and keep rocking.

**Comment by Garsondee** [comment]
Thank you for the advice. A completely new version of this is coming out very soon which completely overhauls the UI but I'll try and bear this advice in mind when I build it.

**Comment by Garsondee** [comment]
@117Dios Hopefully the newer version of the UI is working better for you - there is a v3 of the UI which is being conceptualised right now which is even better so I'm closing this issue as being stale. Thank you for your contribution!
