### ISSUE TITLE
Inline rolls missing?

### ISSUE THREAD

**Issue by MightyMushka** [Garsondee/pf2e-roll-manager#47]
Absolutely love the module! Just wondering though if Inline Rolls are supposed to be available within the latest version or if these have been removed? The green dice icon isn't appearing in any journal unfortunately.

**Comment by Truncated** [comment]
I just noticed that. They were fantastic, I hope they return! I had just enabled Monk's Enhanced Journal and thought that was why they disappeared.

They didn't work with Pop-Out though. Minor quibble. Much rather have them in the journal as-is.

**Comment by Garsondee** [comment]
1.55 - Newly released, adds inline skill rolls back into the module. It might function for Pop-Out too now, I haven't had a chance to check that.
