### ISSUE TITLE
not for whole party

### ISSUE THREAD

**Issue by Ulvtand** [Garsondee/pf2e-roll-manager#52]
So that players can only roll for their own tokens and not for everyone in the whole group

**Comment by thejoester** [comment]
Also, on blind rolls it sends a message to the GM with "???" as the results in the summary?

**Comment by Ulvtand** [comment]
I tested the module and all players can see what other players are getting for results.
Now I don't have this module installed anymore, so I can't send pictures

**Comment by farling42** [comment]
To get it to display only your own owned characters, change line 252 from

` const actors = selectedCharacters.map((id) => game.actors.get(id)).filter(actor => actor !== null);`

to

` const actors = selectedCharacters.map((id) => game.actors.get(id)).filter(actor => actor !== null && actor.isOwner);`

**Comment by farling42** [comment]
Version 1.85 contains this improvement

**Comment by Garsondee** [comment]
Thank you Farling42 for this improvement. I'm closing this issue.
