### ISSUE TITLE
Manifest update in Foundry does not update this module

### ISSUE THREAD

**Issue by mgoldstein322** [Garsondee/pf2e-roll-manager#64]
Hello,

When I update this module in Foundry and accept the new manifest (1.85->1.95) nothing is updated. 

I'm on Foundry 12.311.

**Comment by ngPescado** [comment]
Second this ... using both the automated in Foundry as well as the manual point to the 1.95 ... both claim install complete (even when a fresh install) but it only installs the old v1.85. Manifest pointing to wrong version?

**Comment by tenabraex** [comment]
yar, even manually installing from the .json in the 1.95 release installs 1.85

**Comment by havok03** [comment]
![image](https://github.com/user-attachments/assets/04cc12dd-a7c5-42f6-91c7-21dfa621f790)

It looks like 1.85 and 1.95 are both pointing to the same SHA

**Comment by farling42** [comment]
There have been no commits since 1.85.

But also, the manifest link inside module.json should point to "latest" rather than a specific version. (The download link should remain a specific version.)

**Comment by yuri-ccp** [comment]
Yes the 1.95 zip file is the same of 1.85 zip file. So the modules insides are the 1.85, just the outside manifest that was declared as 1.95 (but when foundry unzips the module.zip it uses the 1.85 manifest too).

**Comment by Garsondee** [comment]
Finally, fixed with 1.96 - I hope.
